### PR TITLE
Fixed polymask

### PR DESCRIPTION
**Pull request by aleien**
Polymask is working now!

### CODE REVIEW

**Comment by taflanidi** [comment]
Hi @aleien 

> Polymask is working now!

Actually, no, it's not. And you've made a bug.

Before closing this pull request, I'd be glad to hear the reason why do you think it was broken in the first place.

According to our internal statistics only, over 84 different Android applications incorporate `PolyMaskTextChangedListener` component without any complaints so far. These apps have been published to the Play Store, which basically means we've got a pretty large QA base proving you are wrong.

And you've literally reversed the [hotfix](https://github.com/aleien/input-mask-android/commits/6d7e4cd9b69c961f3fff894b70d8ddd411588425/inputmask/src/main/kotlin/com/redmadrobot/inputmask/PolyMaskTextChangedListener.kt) for the issue #33 previously applied to this file on May 22 this year.

**Comment by aleien** [comment]
Hello, thanks for fast reply (:
Are you sure, that they started using PolyMask after that hotfix was made? Maybe I'm doing something wrong, but it looks broken to me. 
Here, see this gif. I launched sample app from master branch on Android 7.1.1. I also tried emu with 4.1.1, but it worked the same way.
Here I just input 1-9 numbers. 
Image

**Comment by aleien** [comment]
But #33 is really back, yes. That's a shame.

**Comment by taflanidi** [comment]
@aleien 

> Here, see this gif. I launched sample app from master branch on Android 7.1.1. I also tried emu with 4.1.1, but it worked the same way.

Okay, I'll need to look into this a little bit more. Looks awkward, indeed. It might have happened, the calculated affinity for each step is equal for both «+7 ...» and «8 ...» formats, which brings confusion to the algorithm. 

But it should've been using the first — the "base" — `Mask` instance in this case, ergo there might be something else. I'll come back to you with the results, so stay tuned.

Thanks.

**Comment by aleien** [comment]
Hi!

I looked up and came up with new fix. And it handles #33 alright.
So, the problem was that if you have sequence like {-2, -1, 0, 1} for masks, and primary affinity 2, it would be inserted in 0 position (with result of {2, -2, -1, 0, 1}). So each time it would choose different, incorrect mask.

But I still see one more problem, that is little bit deeper - it calculates affinity not too good(
I.e. if it has masks like "+7 (000)..." as base, "8 (000) ..." and "+1 (000) ..." for input "5" it will choose "+1", and calculate it's affinity higher that base. I'll go check it out too now.

**Comment by aleien** [comment]
Here are some of my thoughts, but I'd like to discuss them with you before implementing.

1) Seems that affinity score will be higher for "+1(000) ..." than for "+7 (000)..." for "+5" input because of whitespace. Is it necessary to use whitespaces in affinity calculation? Maybe if we ignore them when calculating affinity, it will help defining which mask is better match.

2) Also it's needed to think about affinities for cases like "+31-..." and "+32-..." - mask won't let you input "+32-..." because it'll format it as "+31-...". How about not applying mask, until we're certain, that it is really that mask? I.e. affinity > 0? I am not yet sure it'll work, but it may.

Hoping to hear your thoughts on this matter.

**Comment by taflanidi** [comment]
Fixed.

**Pull request closed without merging**
